version: "3"
services:
  rke2-1-26:
    build:
      context: ./
      args:
        RKE2_VERSION: v1.26.10+rke2r1
    image: seanly/rke2-demo:v1.26.10-rke2r1
  rke2-1-27:
    build:
      context: ./
      args:
        RKE2_VERSION: v1.27.7+rke2r1
    image: seanly/rke2-demo:v1.27.7-rke2r1