# server: https://rke2-vip.lan:9345
# token: xxx or `cat /var/lib/rancher/rke2/server/token`

write-kubeconfig-mode: "0644"

cluster-cidr: "192.168.60.0/24"
service-cidr: "192.168.61.0/24"

service-node-port-range: 30000-32767

tls-san:
  - "127.0.0.1"
  - "192.168.2.189"
  - "192.168.2.183"
  - "192.168.2.172"
  - "rke2-node1.lan"
  - "rke2-node2.lan"
  - "rke2-node3.lan"

cni: calico

kube-proxy-arg:
  - "proxy-mode=ipvs"

kubelet-arg:
  - "max-pods=110"

disable:
  - rke2-ingress-nginx

# node-label:
#   - "foo=bar"

disable-cloud-controller: true
selinux: false
debug: false
